/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health endpoint used only to verify backend and database connectivity.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_tickets_get"];
        put?: never;
        /** Create Ticket */
        post: operations["create_ticket_api_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket_api_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Ticket */
        patch: operations["update_ticket_api_tickets__ticket_id__patch"];
        trace?: never;
    };
    "/api/tickets/{ticket_id}/comentarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ticket Comments */
        get: operations["list_ticket_comments_api_tickets__ticket_id__comentarios_get"];
        put?: never;
        /** Add Ticket Comment */
        post: operations["add_ticket_comment_api_tickets__ticket_id__comentarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/transicion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Ticket State */
        post: operations["transition_ticket_state_api_tickets__ticket_id__transicion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Ticket Webhook */
        post: operations["ingest_ticket_webhook_api_webhooks_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** TicketCommentCreate */
        TicketCommentCreate: {
            /** Autor */
            autor?: string | null;
            /** Contenido */
            contenido: string;
        };
        /** TicketCommentRead */
        TicketCommentRead: {
            /** Autor */
            autor: string | null;
            /** Contenido */
            contenido: string;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /** Id */
            id: number;
            /** Ticket Id */
            ticket_id: number;
        };
        /** TicketCreate */
        TicketCreate: {
            /** Asignado A */
            asignado_a?: string | null;
            /** Descripcion */
            descripcion?: string | null;
            /**
             * Prioridad
             * @default medium
             */
            prioridad: string;
            /** Titulo */
            titulo: string;
        };
        /** TicketRead */
        TicketRead: {
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
            /** Asignado A */
            asignado_a: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /** Descripcion */
            descripcion: string | null;
            /** Estado */
            estado: string;
            /** Id */
            id: number;
            /** Prioridad */
            prioridad: string;
            /** Titulo */
            titulo: string;
        };
        /**
         * TicketSortBy
         * @enum {string}
         */
        TicketSortBy: "id" | "creado_en" | "actualizado_en" | "prioridad" | "estado" | "asignado_a";
        /** TicketStateTransition */
        TicketStateTransition: {
            /** Estado */
            estado: string;
        };
        /** TicketStateTransitionConflict */
        TicketStateTransitionConflict: {
            /** Error */
            error: string;
            /** Estado Actual */
            estado_actual: string;
            /** Estado Objetivo */
            estado_objetivo: string;
            /** Mensaje */
            mensaje: string;
            /** Transiciones Permitidas */
            transiciones_permitidas: string[];
        };
        /** TicketUpdate */
        TicketUpdate: {
            /** Asignado A */
            asignado_a?: string | null;
            /** Descripcion */
            descripcion?: string | null;
            /** Estado */
            estado?: string | null;
            /** Prioridad */
            prioridad?: string | null;
            /** Titulo */
            titulo?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WebhookTicketIngestRequest */
        WebhookTicketIngestRequest: {
            /** Event Id */
            event_id: string;
            ticket: components["schemas"]["WebhookTicketPayload"];
        };
        /** WebhookTicketPayload */
        WebhookTicketPayload: {
            /** Asignado A */
            asignado_a?: string | null;
            /** Descripcion */
            descripcion?: string | null;
            /**
             * Prioridad
             * @default medium
             */
            prioridad: string;
            /** Titulo */
            titulo: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_tickets_api_tickets_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                estado?: string | null;
                prioridad?: string | null;
                asignado_a?: string | null;
                creado_desde?: string | null;
                creado_hasta?: string | null;
                actualizado_desde?: string | null;
                actualizado_hasta?: string | null;
                sort_by?: components["schemas"]["TicketSortBy"];
                sort_order?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticket_api_tickets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_api_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ticket_api_tickets__ticket_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRead"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketStateTransitionConflict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ticket_comments_api_tickets__ticket_id__comentarios_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketCommentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_ticket_comment_api_tickets__ticket_id__comentarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCommentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketCommentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_ticket_state_api_tickets__ticket_id__transicion_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketStateTransition"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRead"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketStateTransitionConflict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_ticket_webhook_api_webhooks_tickets_post: {
        parameters: {
            query?: never;
            header: {
                "X-Deskly-Timestamp": number;
                "X-Deskly-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookTicketIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
